services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8000:8000" # API port mapping moved here
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    restart: unless-stopped

  api:
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
