HEARTBEAT_INTERVAL = 30
WORKER_IDLE_SLEEP = 1
WORKER_POLL_BACKOFF = 2
STREAM_UPDATE_INTERVAL = 1
BOOTSTRAP_CHECK_INTERVAL = 3
IDLE_SLEEP = 3600

STOPPED_BY_USER = "Stopped by user"

QUEUE_QUICK = "quick"
QUEUE_AI = "ai"

JOB_AI_NOTE_VIDEO = "ai_note_video"
JOB_QUICK_NOTE_VIDEO = "quick_note_video"
